name: meny_admin
description: Meny Admin - easily create and manage menus for your restaurant

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.14
  cloud_functions: ^3.2.4
  data_table_2: ^2.3.6
  doppelsoft_core:
    git:
      url: git@github.com:doppelsoft-io/doppelsoft-core.git
  doppelsoft_ui:
    git:
      url: git@github.com:doppelsoft-io/doppelsoft-ui.git
  firebase_auth: ^3.3.17
  firebase_core: ^1.1.1
  firebase_storage: ^10.2.15
  flutter:
    sdk: flutter
  flutter_reorderable_list: ^1.2.0
  font_awesome_flutter: ^10.1.0
  freezed: ^2.0.2
  freezed_annotation: ^2.0.1
  get_it: ^7.2.0
  go_router: ^4.2.7
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5
  json_annotation: null
  json_serializable: null
  meny_core:
    git:
      url: git@github.com:doppelsoft-io/meny-core.git
  qr_flutter: ^4.0.0

dev_dependencies:
  build_runner: null
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

dependency_overrides:
  doppelsoft_core:
    path: ../doppelsoft-core
  doppelsoft_ui:
    path: ../doppelsoft-ui
  meny_core:
    path: ../meny-core

flutter:
  uses-material-design: true

  assets:
    - env
