name: meny
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.14
  cloud_functions: ^3.2.4
  core:
    path: ../core
  cupertino_icons: ^1.0.3
  dartz: ^0.10.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.17
  firebase_core: ^1.1.1
  firebase_storage: ^10.2.15
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.3
  flutter_reorderable_list: ^1.2.0
  font_awesome_flutter: ^10.1.0
  freezed: ^2.0.2
  freezed_annotation: ^2.0.1
  get_it: ^7.2.0
  google_fonts: ^2.1.1
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5
  json_annotation: null
  json_serializable: null
  overlay_support: ^1.2.1
  qr_flutter: ^4.0.0
  responsive_builder: ^0.4.2
  responsive_framework: ^0.1.7
  shimmer: ^2.0.0
  universal_platform: ^1.0.0+1

dev_dependencies:
  build_runner: null
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
