name: meny_admin
description: Meny Admin - easily create and manage menus for your restaurant

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  data_table_2: ^2.4.2
  doppelsoft_core:
    git:
      url: git@github.com:doppelsoft-io/doppelsoft-core.git
  doppelsoft_ui:
    git:
      url: git@github.com:doppelsoft-io/doppelsoft-ui.git
  flutter:
    sdk: flutter
  flutter_reorderable_list: ^1.2.0
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.2.0
  go_router: ^5.2.0
  json_annotation: ^4.8.0
  meny_core:
    git:
      url: git@github.com:doppelsoft-io/meny-core.git
  qr_flutter: ^4.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1

dependency_overrides:
  doppelsoft_core:
    path: ../doppelsoft-core
  doppelsoft_ui:
    path: ../doppelsoft-ui
  meny_core:
    path: ../meny-core
flutter:
  uses-material-design: true

  assets:
    - env
