name: Deploy to Firebase Hosting (dev)

env:
  PROJECT_ID: meny-admin-production
  TARGET_FILE: lib/main_production.dart
  FLAGSMITH_ENVIRONMENT_KEY: ${{ secrets.FLAGSMITH_ENVIRONMENT_KEY_PROD }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

on:
  push:
    branches: ["main"]

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build_web:
    name: Build Flutter Web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.MENY_CORE_SSH_DEPLOY_KEY }}
            ${{ secrets.DOPPELSOFT_CORE_SSH_DEPLOY_KEY }}
            ${{ secrets.DOPPELSOFT_UI_SSH_DEPLOY_KEY }}
      - name: Create env
        run: |
          touch env
          echo "FLAGSMITH_ENVIRONMENT_KEY=${{ env.FLAGSMITH_ENVIRONMENT_KEY }}" >> env
          echo "SENTRY_DSN=${{ env.SENTRY_DSN }}" >> env
          cat env
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.3
          channel: 'stable'
          cache: true
      - name: run pub get
        run: flutter pub get
      - run: flutter config --enable-web
      - name: Build web release
        run: flutter build web --target ${{ env.TARGET_FILE }} --web-renderer canvaskit --release
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --except functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ env.PROJECT_ID }}
