name: Deploy to Firebase Hosting (dev)

on:
  push:
    branches: ["development"]

jobs:
  build_web:
    name: Build Flutter Web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.0.5
          channel: 'stable'
          cache: true
      - name: run pub get
        run: flutter pub get
      - name: Build web release
        run: flutter build web --target lib/main_dev.dart --web-renderer canvaskit --release
